"""Unit tests for the document template independent of any owl-semaphore checkout."""

from __future__ import annotations

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from owl_semaphore_press import (  # noqa: E402
    PressConfig,
    banner_tuple_line,
    build_typst_document,
    states,
    typst_str,
)


def _cfg(**overrides) -> PressConfig:
    defaults = dict(
        release_label="v9.9.9",
        author="Test Author",
        orcid="0000-0000-0000-0000",
        repo_url="github.com/example/consumer",
        version_doi="10.5281/zenodo.111",
        concept_doi="10.5281/zenodo.222",
        previous_version=("v9.9.8", "10.5281/zenodo.333"),
        prior_versions=(("v9.9.7", "10.5281/zenodo.444"),),
    )
    defaults.update(overrides)
    return PressConfig(**defaults)


def _doc(**overrides) -> dict:
    s = states.CRITICAL
    defaults = dict(
        md="DOC.md", pdf="DOC.pdf",
        badge="assets/badge.png", contact_sheet="assets/contact.png",
        color=s.color, color_rgb=s.color_rgb, label=s.label,
        state_token=s.token, title="Test Doc", subtitle_typst="Subtitle",
        mathline=s.mathline, quote=s.quote, standard_ref=s.standard_ref,
        contact_caption="Contact Caption", pdf_subject="Subject",
    )
    defaults.update(overrides)
    return defaults


class BannerTupleTest(unittest.TestCase):
    def test_exact_format(self):
        cfg = _cfg()
        line = banner_tuple_line(cfg, "CRITICAL",
                                 states.CRITICAL.mathline, states.CRITICAL.quote)
        self.assertEqual(
            line,
            'BANNER-TUPLE :: STATE=CRITICAL :: '
            'TRANSFORM=T = C2    det = +1    (x, y) -> (-x, -y) :: '
            'QUOTE="This inverts the standard." :: VERSION=v9.9.9 :: '
            'VERSION-DOI=10.5281/zenodo.111 :: CONCEPT-DOI=10.5281/zenodo.222 :: '
            'PREVIOUS-VERSION-DOI=10.5281/zenodo.333',
        )

    def test_banner_tuple_lands_in_document(self):
        out = build_typst_document(_doc(), "BODY\n", _cfg())
        self.assertIn("BANNER-TUPLE :: STATE=CRITICAL", out)


class TemplateTest(unittest.TestCase):
    def test_contact_width_default_and_override(self):
        cfg = _cfg()
        self.assertIn('width: 85%', build_typst_document(_doc(), "B", cfg))
        self.assertIn('width: 90%',
                      build_typst_document(_doc(contact_width="90%"), "B", cfg))

    def test_body_is_embedded_verbatim(self):
        body = "= UNIQUE-BODY-MARKER\ncontent line\n"
        self.assertIn(body, build_typst_document(_doc(), body, _cfg()))

    def test_provenance_stamp_present(self):
        out = build_typst_document(_doc(), "B", _cfg())
        self.assertTrue(out.startswith("// Owl Semaphore PDF — generated by "
                                       "owl-semaphore-press "))

    def test_escaping(self):
        self.assertEqual(typst_str('a "b" \\c'), 'a \\"b\\" \\\\c')
        out = build_typst_document(_doc(title='Quo"te'), "B", _cfg())
        self.assertIn('Quo\\"te', out)

    def test_ledger_contains_all_four_states(self):
        out = build_typst_document(_doc(), "B", _cfg())
        for s in states.STATES:
            self.assertIn(f"[{s.token}]", out)

    def test_doi_family_rendered(self):
        out = build_typst_document(_doc(), "B", _cfg())
        self.assertIn("PRIOR-V9.9.7-DOI 10.5281/zenodo.444", out)
        self.assertIn("v9.9.8 DOI 10.5281/zenodo.333", out)
        self.assertIn("DOI 10.5281/zenodo.111 · CC-BY-4.0", out)


class FirstReleaseConfigTest(unittest.TestCase):
    """A first release has no previous/prior versions — no dangling markers."""

    def _first_cfg(self, **overrides):
        return _cfg(previous_version=("", ""), prior_versions=(), **overrides)

    def test_no_dangling_previous_version_markers(self):
        out = build_typst_document(_doc(), "B", self._first_cfg())
        self.assertNotIn("PREVIOUS-VERSION-DOI", out)
        self.assertNotIn(" ()", out)

    def test_no_bare_linebreak_line_for_empty_priors(self):
        out = build_typst_document(_doc(), "B", self._first_cfg())
        for line in out.splitlines():
            self.assertNotEqual(line.strip(), "\\",
                                "empty prior_versions left a bare line break")

    def test_banner_tuple_omits_empty_doi_fields(self):
        cfg = self._first_cfg(concept_doi="")
        line = banner_tuple_line(cfg, "CRITICAL", "T", '"q"')
        self.assertNotIn("CONCEPT-DOI", line)
        self.assertNotIn("PREVIOUS-VERSION-DOI", line)
        self.assertTrue(line.endswith("VERSION-DOI=10.5281/zenodo.111"))

    def test_footer_without_version_doi(self):
        out = build_typst_document(_doc(), "B", self._first_cfg(version_doi=""))
        self.assertNotIn("[DOI  ·", out)
        self.assertIn("[CC-BY-4.0]", out)


class KeywordsBlockTest(unittest.TestCase):
    def test_keywords_are_escaped(self):
        cfg = _cfg(keywords_prefix=('He said "hi"', "b", "c", "d"))
        out = build_typst_document(_doc(), "B", cfg)
        self.assertIn('"He said \\"hi\\""', out)

    def test_empty_prefix_renders_single_valid_line(self):
        cfg = _cfg(keywords_prefix=())
        out = build_typst_document(_doc(), "B", cfg)
        self.assertNotIn("keywords: (,", out)
        self.assertIn('keywords: ("CRITICAL", "DNS Tool", "accessibility", '
                      '"metacognition"),', out)

    def test_paths_are_escaped_in_string_context(self):
        out = build_typst_document(_doc(badge='we"ird.png'), "B", _cfg())
        self.assertIn('#image("we\\"ird.png", width: 140pt)', out)


class StatesTest(unittest.TestCase):
    def test_canonical_tuples_unchanged(self):
        # The four canonical state-operator tuples are normative; a change
        # here is a spec change, not a refactor.
        self.assertEqual(states.NORMATIVE.mathline,
                         "T = I    det = +1    (x, y) -> (x, y)")
        self.assertEqual(states.NON_NORMATIVE.mathline,
                         "T = sigma_v    det = -1    (x, y) -> (-x, y)")
        self.assertEqual(states.CRITICAL.mathline,
                         "T = C2    det = +1    (x, y) -> (-x, -y)")
        self.assertEqual(states.METACOGNITIVE.mathline,
                         "T = sigma_h    det = -1    (x, y) -> (x, -y)")
        self.assertEqual(
            [s.color for s in states.STATES],
            ["#d4a853", "#316964", "#990f1e", "#8C4191"],
        )


if __name__ == "__main__":
    unittest.main()
